# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b49d149c6653a5457869407c514ad70aa2a5aeaf1fabdab57193f6355dedda23b36141633c9d1e61edd91df4fe42cd1767a209a871153c69420dbd05310befb

test:
  secret_key_base: 8036038936b6e87edae87acf9e487ab031a223ce9517f17f13308b38ef3873a7b7f71d02a7658e92bd468fa0f0967bdda22c49a5191f3b155594e1981e71f51f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
