headings = Heading.create([
  { title: "vanity - production types", rank: 10 },
  { title: "vanity - general admin", rank: 20 },
  { title: "vanity - development", rank: 30 },
  { title: "vanity - digital media", rank: 40 },
  { title: "vanity - education", rank: 50 },
  { title: "vanity - enterprises", rank: 60 },
  { title: "vanity - marketing", rank: 70 },
  { title: "hacks - orphaned events", rank: 80 },
  { title: "hacks", rank: 90 },
  { title: "restructures - people", rank: 100 },
  { title: "restructures - current site", rank: 110 },
  { title: "added by the Voom", rank: 120 }
])

prod = Heading.find(1)
admin = Heading.find(2)
dev = Heading.find(3)
digital = Heading.find(4)
education = Heading.find(5)
enterprises = Heading.find(6)
marketing = Heading.find(7)
orphaned = Heading.find(8)
hacks = Heading.find(9)
people = Heading.find(10)
curr = Heading.find(11)
voom = Heading.find(12)

types = Type.create([
  { status_code: 301, name: :permanent },
  { status_code: 302, name: :temporary },
  { status_code: 410, name: :gone },
])

permanent = Type.find_by_name(:permanent)
temporary = Type.find_by_name(:temporary)
gone = Type.find_by_name(:gone)

redirects = Redirect.create([
  # Vanity - production types
  { source: '/24preludes', target: 'http://www.roh.org.uk/productions/24-preludes-by-alexei-ratmansky', heading: prod, type: permanent },
  { source: '/aeternum', target: 'http://www.roh.org.uk/productions/aeternum-by-christopher-wheeldon', heading: prod, type: permanent },
  { source: '/ageofanxiety', target: 'http://www.roh.org.uk/mixed-programmes/ceremony-of-innocence-the-age-of-anxiety-aeternum?utm_campaign=ageofanxiety&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/aakashodedra', target: 'http://www.roh.org.uk/productions/murmur-inked-by-aakash-odedra?utm_campaign=aakashodedra&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/alice', target: 'http://www.roh.org.uk/productions/alices-adventures-in-wonderland-by-christopher-wheeldon', heading: prod, type: permanent },
  { source: '/ancients', target: 'http://www.roh.org.uk/productions/brand-new-ancients-by-kate-tempest?utm_campaign=ancients&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/annanicole', target: 'http://www.roh.org.uk/productions/anna-nicole-by-richard-jones?utm_campaign=annanicole&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/apollomixed', target: 'http://www.roh.org.uk/mixed-programmes/apollo-aeternum-24-preludes', heading: prod, type: permanent },
  { source: '/ariadne', target: 'http://www.roh.org.uk/productions/ariadne-auf-naxos-by-christof-loy', heading: prod, type: permanent },
  { source: '/ashton', target: 'http://www.roh.org.uk/mixed-programmes/la-valse-meditation-from-thas-voices-of-spring-monotones-i-and-ii-marguerite-and-armand', heading: prod, type: permanent },
  { source: '/ashtonmixed', target: 'http://www.roh.org.uk/mixed-programmes/scenes-de-ballet-five-brahms-waltzes-in-the-manner-of-isadora-duncan-symphonic-variations-a-month-in-the-country?utm_campaign=ashtonmixed&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/atthis', target: 'http://www.roh.org.uk/productions/atthis-by-netia-jones?utm_campaign=atthis&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/babyo', target: 'http://www.roh.org.uk/productions/babyo-by-rachel-drury?utm_campaign=babyo&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/balletblack', target: 'http://www.roh.org.uk/productions/ballet-black-by-various', heading: prod, type: permanent },
  { source: '/balletboyz', target: 'http://www.roh.org.uk/productions/balletboyz-thetalent?utm_campaign=balletboyz&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/balletdelorraine', target: 'http://www.roh.org.uk/productions/shaker-loops-cover-by-various?utm_campaign=balletdelorraine&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/ballo', target: 'http://www.roh.org.uk/productions/un-ballo-in-maschera-by-katharina-thoma?utm_campaign=ballo&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/barbiere', target: 'http://www.roh.org.uk/productions/il-barbiere-di-siviglia-by-moshe-leiser-and-patrice-caurier', heading: prod, type: permanent },
  { source: '/bayadere', target: 'http://www.roh.org.uk/productions/la-bayadere-by-natalia-makarova', heading: prod, type: permanent },
  { source: '/belikewater', target: 'http://www.roh.org.uk/productions/be-like-water-by-hetain-patel', heading: prod, type: permanent },
  { source: '/benfolds', target: 'http://www.roh.org.uk/productions/ben-folds-with-ymusic-by-ben-folds?utm_campaign=benfolds&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/bernballet', target: 'http://www.roh.org.uk/productions/witch-hunt-by-cathy-marston', heading: prod, type: permanent },
  { source: '/birthdaytriple', target: 'http://www.roh.org.uk/mixed-programmes/birthday-offering-a-month-in-the-country-les-noces-by-frederick-ashton', heading: prod, type: permanent },
  { source: '/boccanegra', target: 'http://www.roh.org.uk/productions/simon-boccanegra-by-elijah-moshinsky', heading: prod, type: permanent },
  { source: '/boheme', target: 'http://www.roh.org.uk/productions/la-boheme-by-john-copley?utm_campaign=boheme&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/boonham', target: 'http://www.roh.org.uk/productions/ex-nihilothe-human-edge-by-mayuri-boonham?utm_campaign=boonham&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/bravofigaro', target: 'http://www.roh.org.uk/productions/bravo-figaro-by-mark-thomas', heading: prod, type: permanent },
  { source: '/butterfly', target: 'http://www.roh.org.uk/productions/madama-butterfly-by-moshe-leiser-and-patrice-caurier?utm_campaign=butterfly&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/cafekafka', target: 'http://www.roh.org.uk/productions/the-commission-cafe-kafka-by-annabel-arden?utm_campaign=cafekafka&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/callow', target: 'http://www.roh.org.uk/productions/inside-wagners-head-by-simon-stokes', heading: prod, type: permanent },
  { source: '/canticles', target: 'http://www.roh.org.uk/productions/the-canticles-by-neil-bartlett-and-paule-constable', heading: prod, type: permanent },
  { source: '/capriccio', target: 'http://www.roh.org.uk/productions/capriccio-in-concert', heading: prod, type: permanent },
  { source: '/carmelites', target: 'http://www.roh.org.uk/productions/dialogues-des-carmelites-by-robert-carsen?utm_campaign=carmelites&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/carmen', target: 'http://www.roh.org.uk/productions/carmen-by-francesca-zambello?utm_source=print&utm_medium=bimonthly&utm_campaign=carmen', heading: prod, type: permanent },
  { source: '/cassandra', target: 'http://www.roh.org.uk/productions/cassandra-by-ludovic-ondiviela?utm_campaign=cassandra&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/chameleon', target: 'http://www.roh.org.uk/productions/pictures-we-make-by-gemma-nixon?utm_source=print&utm_medium=bimonthly&utm_campaign=chameleon', heading: prod, type: permanent },
  { source: '/chenier', target: 'http://www.roh.org.uk/productions/andrea-chenier-by-david-mcvicar?utm_campaign=chenier&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/chroma', target: 'http://www.roh.org.uk/productions/chroma-by-wayne-mcgregor', heading: prod, type: permanent },
  { source: '/citiesofsalt', target: 'http://www.roh.org.uk/productions/cities-of-salt-by-zaid-jabri?utm_campaign=citiesofsalt&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/clairemartin', target: 'http://www.roh.org.uk/productions/claire-martin-by-london-jazz-festival-', heading: prod, type: permanent },
  { source: '/competitions', target: 'http://www.roh.org.uk/policies/terms-and-conditions-of-sale', heading: prod, type: permanent },
  { source: '/cubania', target: 'http://www.roh.org.uk/productions/cubania-by-carlos-acosta', heading: prod, type: permanent },
  { source: '/dawsonmixed', target: 'http://www.roh.org.uk/mixed-programmes/chroma-the-human-seasons-the-rite-of-spring', heading: prod, type: permanent },
  { source: '/doncarlo', target: 'http://www.roh.org.uk/productions/don-carlo-by-nicholas-hytner', heading: prod, type: permanent },
  { source: '/dongiovanni', target: 'http://www.roh.org.uk/productions/don-giovanni-by-kasper-holten?utm_campaign=dongiovanni&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/donna', target: 'http://www.roh.org.uk/productions/la-donna-del-lago-by-john-fulljames', heading: prod, type: permanent },
  { source: '/donquixote', target: 'http://www.roh.org.uk/productions/don-quixote-by-carlos-acosta', heading: prod, type: permanent },
  { source: '/draftworks', target: 'http://www.roh.org.uk/productions/draft-works', heading: prod, type: permanent },
  { source: '/dreammixed', target: 'http://www.roh.org.uk/mixed-programmes/the-dream-connectome-the-concert', heading: prod, type: permanent },
  { source: '/dusautoy', target: 'http://www.roh.org.uk/productions/marcus-du-sautoy-by-marcus-du-sautoy', heading: prod, type: permanent },
  { source: '/earnest', target: 'http://www.roh.org.uk/productions/the-importance-of-being-earnest-by-ramin-gray', heading: prod, type: permanent },
  { source: '/elektra', target: 'http://www.roh.org.uk/productions/elektra-by-charles-edwards', heading: prod, type: permanent },
  { source: '/elisir', target: 'http://www.roh.org.uk/productions/lelisir-damore-by-laurent-pelly', heading: prod, type: permanent },
  { source: '/elves', target: 'http://www.roh.org.uk/productions/elves-and-the-shoemaker-by-daniel-de-andrade?utm_campaign=elves&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/eto', target: 'http://www.roh.org.uk/productions/albert-herring-by-christopher-rolls', heading: prod, type: permanent },
  { source: '/eugeneonegin', target: 'http://www.roh.org.uk/productions/eugene-onegin-by-kasper-holten', heading: prod, type: permanent },
  { source: '/eurydice', target: 'http://www.roh.org.uk/productions/orphee-et-eurydice-by-hofesh-shechter-and-john-fulljames?utm_campaign=eurydice&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/falstaff', target: 'http://www.roh.org.uk/productions/falstaff-by-robert-carsen?utm_campaign=falstaff&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/faunmixed', target: 'http://www.roh.org.uk/mixed-programmes/afternoon-of-a-faun-in-the-night-song-of-the-earth?utm_campaign=faunmixed&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/familysundays', target: 'http://www.roh.org.uk/functions/family-sundays', heading: prod, type: permanent },
  { source: '/faust', target: 'http://www.roh.org.uk/productions/faust-by-david-mcvicar?utm_campaign=faust&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/figaro', target: 'http://www.roh.org.uk/productions/le-nozze-di-figaro-by-david-mcvicar?utm_campaign=figaro&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/fille', target: 'http://www.roh.org.uk/productions/la-fille-mal-gardee-by-frederick-ashton?utm_campaign=fille&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/firebirdmixed', target: 'http://www.roh.org.uk/mixed-programmes/the-firebird-in-the-night-raymonda-act-iii', heading: prod, type: permanent },
  { source: '/firework', target: 'http://www.roh.org.uk/productions/the-firework-makers-daughter-by-john-fulljames', heading: prod, type: permanent },
  { source: '/flower', target: 'http://www.roh.org.uk/productions/the-killing-flower-by-michael-mccarthy', heading: prod, type: permanent },
  { source: '/foolsparadise', target: 'http://www.roh.org.uk/productions/fools-paradise-by-christopher-wheeldon', heading: prod, type: permanent },
  { source: '/foscari', target: 'http://www.roh.org.uk/productions/i-due-foscari-by-thaddeus-strassberger?utm_campaign=foscari&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/fused', target: 'http://www.roh.org.uk/productions/fused-festival', heading: prod, type: permanent },
  { source: '/gardee', target: 'http://www.roh.org.uk/productions/la-fille-mal-gardee-by-frederick-ashton', heading: prod, type: permanent },
  { source: '/giselle', target: 'http://www.roh.org.uk/productions/giselle-by-peter-wright?utm_source=print&utm_medium=bimonthly&utm_campaign=giselle', heading: prod, type: permanent },
  { source: '/glare', target: 'http://www.roh.org.uk/productions/glare-by-thaddeus-strassberger?utm_campaign=glare&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/gloria', target: 'http://www.roh.org.uk/productions/gloria-a-pigtale-by-frederic-wake-walker', heading: prod, type: permanent },
  { source: '/gloriana', target: 'http://www.roh.org.uk/productions/gloriana-by-richard-jones', heading: prod, type: permanent },
  { source: '/greek', target: 'http://www.roh.org.uk/productions/greek-by-music-theatre-wales', heading: prod, type: permanent },
  { source: '/hanselandgretel', target: 'http://www.roh.org.uk/productions/hansel-and-gretel-by-liam-scarlett', heading: prod, type: permanent },
  { source: '/headspacedance', target: 'http://www.roh.org.uk/productions/headspacedance-by-various?utm_campaign=headspacedance&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/hollander', target: 'http://www.roh.org.uk/productions/der-fliegende-hollander-by-tim-albery?utm_campaign=hollander&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/help/digital-guide-faqs', target: 'http://www.roh.org.uk/help/digital-programme-faqs', heading: prod, type: permanent },
  { source: '/idomeneo', target: 'http://www.roh.org.uk/productions/idomeneo-by-martin-kusej?utm_campaign=idomeneo&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/isadora', target: 'http://www.roh.org.uk/productions/five-brahms-waltzes-in-the-manner-of-isadora-duncan-by-frederick-ashton', heading: prod, type: permanent },
  { source: '/jeanabreu', target: 'http://www.roh.org.uk/productions/blood-by-jean-abreu', heading: prod, type: permanent },
  { source: '/jeyasingh', target: 'http://www.roh.org.uk/productions/bayadere-the-ninth-life-by-shobana-jeyasingh?utm_campaign=jeyasingh&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/jewels', target: 'http://www.roh.org.uk/productions/jewels-by-george-balanchine?utm_source=print&utm_medium=bimonthly&utm_campaign=jewels', heading: prod, type: permanent },
  { source: '/JPYA', target: 'http://www.roh.org.uk/productions/young-artists-in-the-linbury-by-jette-parker-young-artists', heading: prod, type: permanent },
  { source: '/jpya', target: 'http://www.roh.org.uk/productions/young-artists-in-the-linbury-by-jette-parker-young-artists', heading: prod, type: permanent },
  { source: '/jpyasummer', target: 'http://www.roh.org.uk/productions/jpya-summer-performance?utm_campaign=jpyasummer&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/jpyaweek', target: 'http://www.roh.org.uk/productions/meet-the-young-artists-week-performance-by-jette-parker-young-artists', heading: prod, type: permanent },
  { source: '/kafka', target: 'http://www.roh.org.uk/productions/kafka-fragments-by-netia-jones', heading: prod, type: permanent },
  { source: '/kaufmann', target: 'http://www.roh.org.uk/productions/jonas-kaufmann-winterreise?utm_campaign=kaufmann&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/kingsize', target: 'http://www.roh.org.uk/productions/king-size-by-christoph-marthaler?utm_campaign=kingsize&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/krolroger', target: 'http://www.roh.org.uk/productions/krol-roger-by-kasper-holten?utm_campaign=krolroger&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/lelisir', target: 'http://www.roh.org.uk/productions/lelisir-damore-by-laurent-pelly?utm_campaign=lelisir&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/limf', target: 'http://www.roh.org.uk/productions/london-international-mime-festival-by-various?utm_campaign=limf&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/lormindo', target: 'http://www.roh.org.uk/productions/lormindo-by-kasper-holten?utm_campaign=lormindo&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/lunchtimerecitals', target: 'http://www.roh.org.uk/recitals/lunchtime-recitals', heading: prod, type: permanent },
  { source: '/macbeth', target: 'http://www.roh.org.uk/productions/macbeth-by-judith-roberts?utm_source=print&utm_medium=bimonthly&utm_campaign=macbeth', heading: prod, type: permanent },
  { source: '/macmillan', target: 'http://www.roh.org.uk/mixed-programmes/concerto-las-hermanas-requiem-by-kenneth-macmillan', heading: prod, type: permanent },
  { source: '/magicflute', target: 'http://www.roh.org.uk/productions/die-zauberflote-by-david-mcvicar?utm_campaign=magicflute&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/mahagonny', target: 'http://www.roh.org.uk/productions/rise-and-fall-of-the-city-of-mahagonny-by-john-fulljames?utm_campaign=mahagonny&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/manon', target: 'http://www.roh.org.uk/productions/manon-by-kenneth-macmillan?utm_campaign=manon&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/manonlescaut', target: 'http://www.roh.org.uk/productions/manon-lescaut-by-jonathan-kent', heading: prod, type: permanent },
  { source: '/marguerite', target: 'http://www.roh.org.uk/productions/marguerite-and-armand-by-frederick-ashton', heading: prod, type: permanent },
  { source: '/mariastuarda', target: 'http://www.roh.org.uk/productions/maria-stuarda-by-patrice-caurier-and-moshe-leiser', heading: prod, type: permanent },
  { source: '/mayerling', target: 'http://www.roh.org.uk/productions/mayerling-by-kenneth-macmillan', heading: prod, type: permanent },
  { source: '/mcgregormixed', target: 'http://www.roh.org.uk/mixed-programmes/rhapsody-tetractys-the-art-of-fugue-gloria', heading: prod, type: permanent },
  { source: '/minotaur', target: 'http://www.roh.org.uk/productions/the-minotaur-by-stephen-langridge', heading: prod, type: permanent },
  { source: '/missfortune', target: 'http://www.roh.org.uk/productions/miss-fortune-by-judith-weir', heading: prod, type: permanent },
  { source: '/monotones', target: 'http://www.roh.org.uk/productions/monotones-i-and-ii-by-frederick-ashton', heading: prod, type: permanent },
  { source: '/mosesundaron', target: 'http://www.roh.org.uk/productions/moses-und-aron-by-jossi-wieler-and-sergio-morabito', heading: prod, type: permanent },
  { source: '/mostboys', target: 'http://www.roh.org.uk/productions/most-of-the-boys-by-ted-huffman', heading: prod, type: permanent },
  { source: '/musicalrumpus', target: 'http://www.roh.org.uk/productions/musical-rumpus-the-mountain-shakers-by-zoe-palmer', heading: prod, type: permanent },
  { source: '/mtw', target: 'http://www.roh.org.uk/productions/in-the-locked-room-by-huw-watkins-and-david-harsent', heading: prod, type: permanent },
  { source: '/nabucco', target: 'http://www.roh.org.uk/productions/nabucco-by-daniele-abbado', heading: prod, type: permanent },
  { source: '/ndcw', target: 'http://www.roh.org.uk/productions/water-stories-noces-virtual-descent-by-stephen-petronio?utm_source=print&utm_medium=bimonthly&utm_campaign=ndcw', heading: prod, type: permanent },
  { source: '/newtriple', target: 'http://www.roh.org.uk/productions/viscera-infra-fools-paradise-by-wayne-mcgregor', heading: prod, type: permanent },
  { source: '/nobodysbaby', target: 'http://www.roh.org.uk/productions/nobodys-baby-the-worlds-greatest-show-by-arthur-pita', heading: prod, type: permanent },
  { source: '/northernballet', target: 'http://www.roh.org.uk/productions/northern-ballet-by-kenneth-tindall', heading: prod, type: permanent },
  { source: '/northernballetmixed', target: 'http://www.roh.org.uk/productions/the-architect-mixed-programme-by-various?utm_campaign=northernballetmixed&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/nutcracker', target: 'http://www.roh.org.uk/productions/the-nutcracker-by-peter-wright', heading: prod, type: permanent },
  { source: '/obvsc', target: 'http://www.roh.org.uk/productions/orquesta-buena-vista-social-club?utm_campaign=obvsc&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/orfeo', target: 'http://www.roh.org.uk/productions/orfeo-by-michael-boyd?utm_campaign=orfeo&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/onebigstage', target: 'http://www.roh.org.uk/productions/one-big-stage', heading: prod, type: permanent },
  { source: '/onegin', target: 'http://www.roh.org.uk/productions/onegin-by-john-cranko', heading: prod, type: permanent },
  { source: '/operalia', target: 'http://www.roh.org.uk/productions/placido-domingos-operalia-by-placido-domingo?utm_campaign=operalia&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/operashots', target: 'http://www.roh.org.uk/productions/operashots-by-various', heading: prod, type: permanent },
  { source: '/otello', target: 'http://www.roh.org.uk/productions/otello-by-elijah-moshinsky', heading: prod, type: permanent },
  { source: '/pagodas', target: 'http://www.roh.org.uk/productions/the-prince-of-the-pagodas-by-kenneth-macmillan', heading: prod, type: permanent },
  { source: '/pappanoconcert', target: 'http://www.roh.org.uk/productions/antonio-pappano-and-the-orchestra-of-the-royal-opera-house-by-orchestral-concert?utm_campaign=pappanoconcert&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/parsifal', target: 'http://www.roh.org.uk/productions/parsifal-by-stephen-langridge', heading: prod, type: permanent },
  { source: '/peterpan', target: 'http://www.roh.org.uk/productions/peter-pan-by-keith-warner?utm_campaign=peterpan&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/phoenix', target: 'http://www.roh.org.uk/productions/shift-shadows-document-mapping-by-various?utm_campaign=phoenix&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/polkatheatre', target: 'http://www.roh.org.uk/productions/dot-squiggle-and-rest-by-joy-haynes?utm_campaign=polkatheatre&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/quarters', target: 'http://www.roh.org.uk/productions/three-and-four-quarters-by-christopher-akrill-and-charlotte-broom', heading: prod, type: permanent },
  { source: '/quartett', target: 'http://www.roh.org.uk/productions/quartett-by-john-fulljames', heading: prod, type: permanent },
  { source: '/random', target: 'http://www.roh.org.uk/productions/far-by-wayne-mcgregor', heading: prod, type: permanent },
  { source: '/ravengirl', target: 'http://www.roh.org.uk/mixed-programmes/raven-girl-symphony-in-c', heading: prod, type: permanent },
  { source: '/rbs', target: 'http://www.roh.org.uk/productions/the-royal-ballet-school-annual-performance-by-the-royal-ballet-school', heading: prod, type: permanent },
  { source: '/rbssummer', target: 'http://www.roh.org.uk/productions/the-royal-ballet-school-summer-performances-by-the-royal-ballet-school?utm_campaign=rbssummer&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/regiment', target: 'http://www.roh.org.uk/productions/la-fille-du-regiment-by-laurent-pelly', heading: prod, type: permanent },
  { source: '/Richmond', target: 'http://www.roh.org.uk/productions/made-in-the-usa-by-richmond-ballet', heading: prod, type: permanent },
  { source: '/richmond', target: 'http://www.roh.org.uk/productions/made-in-the-usa-by-richmond-ballet', heading: prod, type: permanent },
  { source: '/rigoletto', target: 'http://www.roh.org.uk/productions/rigoletto-by-david-mcvicar', heading: prod, type: permanent },
  { source: '/rite', target: 'http://www.roh.org.uk/productions/the-rite-of-spring-by-kenneth-macmillan', heading: prod, type: permanent },
  { source: '/robert', target: 'http://www.roh.org.uk/productions/robert-le-diable-by-laurent-pelly', heading: prod, type: permanent },
  { source: '/romeo', target: 'http://www.roh.org.uk/productions/romeo-and-juliet-by-kenneth-macmillan', heading: prod, type: permanent },
  { source: '/rondine', target: 'http://www.roh.org.uk/productions/la-rondine-by-nicolas-joel', heading: prod, type: permanent },
  { source: '/salome', target: 'http://www.roh.org.uk/productions/salome-by-david-mcvicar', heading: prod, type: permanent },
  { source: '/schatten', target: 'http://www.roh.org.uk/productions/die-frau-ohne-schatten-by-claus-guth?utm_campaign=schatten&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/sensoryo', target: 'http://www.roh.org.uk/productions/sensoryo-by-rachel-drury?utm_campaign=sensoryo&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/serenademixed', target: 'http://www.roh.org.uk/mixed-programmes/serenade-sweet-violets-dgv-danse-a-grande-vitesse', heading: prod, type: permanent },
  { source: '/shechtermixed', target: 'http://www.roh.org.uk/mixed-programmes/the-four-temperaments-hofesh-shechter-song-of-the-earth?utm_campaign=shectermixed&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/siciliennes', target: 'http://www.roh.org.uk/productions/les-vepres-siciliennes-by-stefan-herheim', heading: prod, type: permanent },
  { source: '/silence', target: 'http://www.roh.org.uk/productions/listen-to-the-silence-by-wouter-van-looy?utm_campaign=silence&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/skin', target: 'http://www.roh.org.uk/productions/written-on-skin-by-katie-mitchell', heading: prod, type: permanent },
  { source: '/sleepingbeauty', target: 'http://www.roh.org.uk/productions/the-sleeping-beauty-by-marius-petipa?utm_campaign=sleepingbeauty&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/sofa', target: 'http://www.roh.org.uk/productions/the-yellow-sofa-by-julian-philips', heading: prod, type: permanent },
  { source: '/springboard', target: 'http://www.roh.org.uk/productions/ballet-central-by-central-school-of-ballet?utm_campaign=springboard&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/sum', target: 'http://www.roh.org.uk/productions/sum-by-max-richter', heading: prod, type: permanent },
  { source: '/swanhunter', target: 'http://www.roh.org.uk/productions/swanhunter-by-hannah-mulder?utm_campaign=swanhunter&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/swanlake', target: 'http://www.roh.org.uk/productions/swan-lake-by-anthony-dowell', heading: prod, type: permanent },
  { source: '/swanlights', target: 'http://www.roh.org.uk/productions/swanlights-by-antony-and-the-johnsons', heading: prod, type: permanent },
  { source: '/sylphide', target: 'http://www.roh.org.uk/productions/ballo-della-regina-la-sylphide-by-simon-bennison', heading: prod, type: permanent },
  { source: '/tale', target: 'http://www.roh.org.uk/productions/the-winters-tale-by-christopher-wheeldon?utm_source=print&utm_medium=medium&utm_campaign=tale', heading: prod, type: permanent },
  { source: '/teeth', target: 'http://www.roh.org.uk/productions/through-his-teeth-by-bijan-sheibani?utm_campaign=teeth&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/telegraphbigquestion', target: 'http://www.roh.org.uk/functions/the-big-question', heading: prod, type: permanent },
  { source: '/thebigquestion', target: 'http://www.roh.org.uk/functions/the-big-question', heading: prod, type: permanent },
  { source: '/thecrackle', target: 'http://www.roh.org.uk/productions/the-crackle-by-matthew-herbert?utm_campaign=thecrackle&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/thecure', target: 'http://www.roh.org.uk/productions/the-corridor-the-cure-by-martin-duncan?utm_campaign=thecure&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/themetamorphosis', target: 'http://www.roh.org.uk/productions/the-metamorphosis-by-arthur-pita', heading: prod, type: permanent },
  { source: '/thetrial', target: 'http://www.roh.org.uk/productions/the-trial-by-michael-mccarthy?utm_campaign=thetrial&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/titian2012', target: 'http://www.roh.org.uk/productions/metamorphosis-titian-2012-by-various', heading: prod, type: permanent },
  { source: '/tosca', target: 'http://www.roh.org.uk/productions/tosca-by-jonathan-kent?utm_campaign=tosca&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/traviata', target: 'http://www.roh.org.uk/productions/la-traviata-by-richard-eyre?utm_campaign=traviata&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/tristan', target: 'http://www.roh.org.uk/productions/tristan-und-isolde-by-christof-loy?utm_campaign=tristan&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },
  { source: '/troyens', target: 'http://www.roh.org.uk/productions/les-troyens-by-david-mcvicar', heading: prod, type: permanent },
  { source: '/turandot', target: 'http://www.roh.org.uk/productions/turandot-by-andrei-serban', heading: prod, type: permanent },
  { source: '/turco', target: 'http://www.roh.org.uk/productions/il-turco-in-italia-by-moshe-leiser-and-patrice-caurier?utm_campaign=turco&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/virtues', target: 'http://www.roh.org.uk/productions/the-virtues-of-things-by-bijan-sheibani?utm_campaign=virtues&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/viscera', target: 'http://www.roh.org.uk/productions/viscera-infra-fools-paradise-by-wayne-mcgregor', heading: prod, type: permanent },
  { source: '/wasp', target: 'http://www.roh.org.uk/productions/the-wasp-factory-by-ben-frost', heading: prod, type: permanent },
  { source: '/whale', target: 'http://www.roh.org.uk/productions/how-the-whale-became-by-natalie-abrahami', heading: prod, type: permanent },
  { source: '/whelan', target: 'http://www.roh.org.uk/productions/wendy-whelan-restless-creature-by-wendy-whelan', heading: prod, type: permanent },
  { source: '/whelanwatson', target: 'http://www.roh.org.uk/productions/whelanwatson-other-stories-by-various?utm_campaign=whelanwatson&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/whitley', target: 'http://www.roh.org.uk/productions/the-measures-taken-by-alexander-whitley?utm_campaign=whitely&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/williamtell', target: 'http://www.roh.org.uk/productions/guillaume-tell-by-damiano-michieletto?utm_campaign=williamtell&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/willows', target: 'http://www.roh.org.uk/productions/the-wind-in-the-willows-by-will-tuckett', heading: prod, type: permanent },
  { source: '/winterstale', target: 'http://www.roh.org.uk/productions/the-winters-tale-by-christopher-wheeldon?utm_campaign=winterstale&utm_medium=short&utm_source=marketing', heading: prod, type: permanent },
  { source: '/woolfworks', target: 'http://www.roh.org.uk/productions/woolf-works-by-wayne-mcgregor?utm_campaign=woolfworks&utm_medium=marketing&utm_source=print', heading: prod, type: permanent },
  { source: '/wozzeck', target: 'http://www.roh.org.uk/productions/wozzeck-by-keith-warner', heading: prod, type: permanent },
  { source: '/zauberflote', target: 'http://www.roh.org.uk/productions/die-zauberflote-by-david-mcvicar', heading: prod, type: permanent },
  { source: '/zoonation', target: 'http://www.roh.org.uk/productions/the-mad-hatters-tea-party-by-various?utm_campaign=zoonation&utm_medium=bimonthly&utm_source=print', heading: prod, type: permanent },

  # Vanity - general admin
  { source: '/access', target: 'http://www.roh.org.uk/visit/access', heading: admin, type: permanent },
  { source: '/annualreview', target: 'http://www.roh.org.uk/about/the-royal-opera-house/annual-review', heading: admin, type: permanent },
  { source: '/firststage', target: 'http://www.roh.org.uk/about/the-royal-opera-house/work-here/first-stage-work-experience-at-the-royal-opera-house', heading: admin, type: permanent },
  { source: '/jobsalert', target: 'http://recruitment.roh.org.uk/emailAlerts.php', heading: admin, type: permanent },
  { source: '/press', target: 'http://www.roh.org.uk/for/press-and-communications', heading: admin, type: permanent },
  { source: '/terms', target: 'http://www.roh.org.uk/policies/terms-and-conditions-of-sale', heading: admin, type: permanent },
  { source: '/workexperience', target: 'http://www.roh.org.uk/about/the-royal-opera-house/work-here/first-stage-work-experience-at-the-royal-opera-house', heading: admin, type: permanent },
  { source: '/workhere', target: 'http://www.roh.org.uk/about/the-royal-opera-house/work-here', heading: admin, type: permanent },

  # Vanity - development
  { source: '/branko', target: 'http://www.roh.org.uk/support/membership/friends?utm_source=print&utm_medium=house&utm_content=branko&utm_campaign=development_promo_nov_2013', heading: dev, type: permanent },
  { source: '/chance', target: 'http://www.roh.org.uk/support/fundraising-appeals/chance-to-dance-appeal', heading: dev, type: permanent },
  { source: '/endowment', target: 'http://www.roh.org.uk/support/leave-a-legacy/royal-opera-house-endowment-fund', heading: dev, type: permanent },
  { source: '/focg', target: 'http://www.roh.org.uk/support/membership/friends', heading: dev, type: permanent },
  { source: '/friends', target: 'http://www.roh.org.uk/support/membership/friends', heading: dev, type: permanent },
  { source: '/fryni', target: 'http://www.roh.org.uk/support/membership/friends?utm_source=print&utm_medium=house&utm_content=fryni&utm_campaign=development_promo_nov_2013', heading: dev, type: permanent },
  { source: '/granddraw2013', target: 'http://www.roh.org.uk/news/swap-the-wintery-british-weather-for-a-beach-in-the-maldives', heading: dev, type: permanent },
  { source: '/granddraw2015', target: 'http://www.raffleentry.org.uk/royaloperahouse', heading: dev, type: permanent },
  { source: '/insiders', target: 'http://www.roh.org.uk/support/membership/friends', heading: dev, type: permanent },
  { source: '/legacy', target: 'http://www.roh.org.uk/support/leave-a-legacy', heading: dev, type: permanent },
  { source: '/louise', target: 'http://www.roh.org.uk/support/membership/friends?utm_source=print&utm_medium=house&utm_content=louise&utm_campaign=development_promo_nov_2013', heading: dev, type: permanent },
  { source: '/membership', target: 'http://www.roh.org.uk/support/membership', heading: dev, type: permanent },
  { source: '/nameaseat', target: 'http://www.roh.org.uk/support/name-a-seat', heading: dev, type: permanent },
  { source: '/patrons', target: 'http://www.roh.org.uk/support/membership/patrons', heading: dev, type: permanent },
  { source: '/pedro', target: 'http://www.roh.org.uk/news/young-artist-profile-stage-director-pedro-ribeiro-on-melding-theatre-and-music', heading: dev, type: permanent },
  { source: '/pencil', target: 'http://www.roh.org.uk/support/donations/fundraising-appeals/season-launch-appeal?utm_source=print&utm_medium=short&utm_campaign=pencil', heading: dev, type: permanent },
  { source: '/pointe', target: 'http://www.roh.org.uk/support/fundraising-appeals/pointe-shoes-appeal', heading: dev, type: permanent },
  { source: '/pointes', target: 'http://www.roh.org.uk/support/donations/fundraising-appeals/pointe-shoes-appeal?utm_source=red_programme&utm_medium=ad&utm_campaign=pointes', heading: dev, type: permanent },
  { source: '/pointeshoesappeal', target: 'http://www.roh.org.uk/support/you/pointe-appeal', heading: dev, type: permanent },
  { source: '/polish', target: 'http://www.roh.org.uk/support/donations/fundraising-appeals/season-launch-appeal?utm_source=print&utm_medium=short&utm_campaign=polish', heading: dev, type: permanent },
  { source: '/scissors', target: 'http://www.roh.org.uk/support/donations/fundraising-appeals/season-launch-appeal?utm_source=print&utm_medium=short&utm_campaign=scissors', heading: dev, type: permanent },
  { source: '/seasonappeal', target: 'http://www.roh.org.uk/support/donations/fundraising-appeals/season-launch-appeal?utm_source=print&utm_medium=short&utm_campaign=seasonappeal', heading: dev, type: permanent },
  { source: '/sewing', target: 'http://www.roh.org.uk/support/fundraising-appeals/sewing-appeal', heading: dev, type: permanent },
  { source: '/shoes', target: 'http://www.roh.org.uk/support/donations/fundraising-appeals/season-launch-appeal?utm_source=print&utm_medium=short&utm_campaign=shoes', heading: dev, type: permanent },
  { source: '/wagner', target: 'http://www.roh.org.uk/support/fundraising-appeals/wagner-appeal', heading: dev, type: permanent },

  # Vanity - digital media
  { source: '/2012', target: 'http://www.roh.org.uk/news/london-2012-festival-at-the-royal-opera-house', heading: digital, type: permanent },
  { source: '/autumn2012', target: 'http://www.roh.org.uk/news/public-booking-useful-information', heading: digital, type: permanent },
  { source: '/autumnpackages', target: 'http://www.roh.org.uk/news/great-savings-with-advance-booking-packages-for-autumn-2013', heading: digital, type: permanent },
  { source: '/barda', target: 'http://www.roh.org.uk/news/major-retrospective-planned-of-the-work-of-photographer-clive-barda', heading: digital, type: permanent },
  { source: '/bookingtrial2015', target: 'http://www.roh.org.uk/news/general-booking-for-summer-2015-season-to-go-on-sale-online-at-8am-on-31-march-2015?utm_source=screens&utm_medium=marketing&utm_campaign=bookingtrial2015', heading: digital, type: permanent },
  { source: '/culturedebate', target: 'http://www.roh.org.uk/news/live-stream-discover-what-the-political-parties-have-to-say-about-arts-and-heritage-in-the-culture-debate', heading: digital, type: permanent },
  { source: '/dancers', target: 'http://www.roh.org.uk/about/the-royal-ballet/artists', heading: digital, type: permanent },
  { source: '/domingo', target: 'http://www.roh.org.uk/news/watch-placido-domingo-in-conversation-event-streamed-live-by-roh-on-12-october-2014', heading: digital, type: permanent },
  { source: '/facebook', target: 'https://www.facebook.com/royaloperahouse', heading: digital, type: permanent },
  { source: '/krolrogerlive', target: 'http://www.roh.org.uk/news/krol-roger-to-be-live-streamed-on-16-may-2015', heading: digital, type: permanent },
  { source: '/livestreaming', target: 'http://www.roh.org.uk/news/tags/live-stream', heading: digital, type: permanent },
  { source: '/operamachine', target: 'http://www.roh.org.uk/opera-machine', heading: digital, type: permanent },
  { source: '/operashorts', target: 'http://www.roh.org.uk/news/watch-opera-shorts-series', heading: digital, type: permanent },
  { source: '/puccini', target: 'http://www.roh.org.uk/people/giacomo-puccini', heading: digital, type: permanent },
  { source: '/royaloperalive', target: 'http://www.roh.org.uk/news/watch-royal-opera-live', heading: digital, type: permanent },
  { source: '/springseasontrailer', target: 'http://www.roh.org.uk/news/watch-spring-season-trailer', heading: digital, type: permanent },
  { source: '/worldballetday', target: 'http://www.roh.org.uk/about/world-ballet-day', heading: digital, type: permanent },

  # Vanity - education
  { source: '/aidadesignchallenge', target: 'http://www.roh.org.uk/learning/schools-and-colleges/design-challenge', heading: education, type: permanent },
  { source: '/apprenticeship', target: 'http://www.roh.org.uk/learning/schools-and-colleges/apprenticeships', heading: education, type: permanent },
  { source: '/apprenticeships', target: 'http://www.roh.org.uk/learning/schools-and-colleges/apprenticeships', heading: education, type: permanent },
  { source: '/bridge', target: 'http://www.roh.org.uk/learning/royal-opera-house-bridge', heading: education, type: permanent },
  { source: '/cinemaforschools', target: 'http://www.roh.org.uk/news/schools-cinema-screenings-alices-adventures-in-wonderland', heading: education, type: permanent },
  { source: '/communitychorus', target: 'http://www.roh.org.uk/learning/learning-in-thurrock/community-chorus', heading: education, type: permanent },
  { source: '/community-chorus', target: 'http://www.roh.org.uk/learning/learning-in-thurrock/community-chorus', heading: education, type: permanent },
  { source: '/culturechange', target: 'http://www.roh.org.uk/about/culture-change', heading: education, type: permanent },
  { source: '/dancedynamic', target: 'http://www.roh.org.uk/learning/teachers/dance-dynamic', heading: education, type: permanent },
  { source: '/designchallenge', target: 'http://www.roh.org.uk/learning/schools-and-colleges/design-challenge', heading: education, type: permanent },
  { source: '/education', target: 'http://www.roh.org.uk/learning', heading: education, type: permanent },
  { source: '/familyperformances', target: 'http://www.roh.org.uk/learning/families/welcome-performances', heading: education, type: permanent },
  { source: '/fanfare', target: 'http://www.roh.org.uk/learning/schools-and-colleges/fanfare', heading: education, type: permanent },
  { source: '/fanfareresources', target: 'http://www.roh.org.uk/learning/schools-and-colleges/fanfare', heading: education, type: permanent },
  { source: '/inspiration', target: 'http://www.roh.org.uk/learning/learning-in-thurrock/inspiration-days', heading: education, type: permanent },
  { source: '/makeyourown', target: 'http://www.roh.org.uk/learning/families/welcome-performances/swan-lake-print-out-and-keep-resources', heading: education, type: permanent },
  { source: '/rm19', target: 'http://www.roh.org.uk/learning/learning-in-thurrock/rm19-youth-singing-group', heading: education, type: permanent },
  { source: '/RM19', target: 'http://www.roh.org.uk/learning/learning-in-thurrock/rm19-youth-singing-group', heading: education, type: permanent },
  { source: '/schoolsmatinees', target: 'http://www.roh.org.uk/learning/schools-and-colleges/schools-matinees', heading: education, type: permanent },
  { source: '/students', target: 'http://www.roh.org.uk/for/rohstudents', heading: education, type: permanent },
  { source: '/studentstandby', target: 'http://www.roh.org.uk/for/students', heading: education, type: permanent },
  { source: '/sleepover', target: 'http://www.roh.org.uk/news/sleepover-at-the-opera-house', heading: education, type: permanent },
  { source: '/teachers', target: 'http://www.roh.org.uk/learning/teachers', heading: education, type: permanent },
  { source: '/thurrock', target: 'http://www.roh.org.uk/about/thurrock', heading: education, type: permanent },
  { source: '/youthopera', target: 'http://www.roh.org.uk/learning/families/youth-opera-company', heading: education, type: permanent },
  { source: '/welcomeperformances', target: 'http://www.roh.org.uk/learning/families/welcome-performances', heading: education, type: permanent },
  { source: '/writeanopera', target: 'http://www.roh.org.uk/news/write-an-opera', heading: education, type: permanent },

  # Vanity - enterprises
  { source: '/cinema', target: 'http://www.roh.org.uk/cinemas', heading: enterprises, type: permanent },
  { source: '/daytimeevents', target: 'http://www.roh.org.uk/services/venue-hire/the-paul-hamlyn-hall-daytime-events', heading: enterprises, type: permanent },
  { source: '/eugenesurvey', target: 'http://www.researchnowsurveys.com/survey/VOP14021309180325CSPP/enter.asp', heading: enterprises, type: permanent },
  { source: '/krolprogramme', target: 'http://www.roh.org.uk/publications/krol-roger-digital-programme', heading: enterprises, type: permanent },
  { source: '/krolprogram', target: 'http://www.roh.org.uk/publications/krol-roger-digital-programme', heading: enterprises, type: permanent },
  { source: '/licensing', target: 'http://www.roh.org.uk/services/brand-licensing', heading: enterprises, type: permanent },
  { source: '/shop', target: 'http://www.roh.org.uk/products/', heading: enterprises, type: permanent },
  { source: '/tea', target: 'http://www.roh.org.uk/functions/tea-at-the-royal-opera-house', heading: enterprises, type: permanent },
  { source: '/services/venue-hire/theriverpavilion', target: 'http://www.roh.org.uk/services/venue-hire/the-river-pavilion', heading: enterprises, type: permanent },
  { source: '/theriverpavilion', target: 'http://www.roh.org.uk/services/venue-hire/the-river-pavilion', heading: enterprises, type: permanent },
  { source: '/theriverpavillion', target: 'http://www.roh.org.uk/services/venue-hire/the-river-pavilion', heading: enterprises, type: permanent },
  { source: '/venuehire/theriverpavilion', target: 'http://www.roh.org.uk/services/venue-hire/the-river-pavilion', heading: enterprises, type: permanent },
  { source: '/venuehire', target: 'http://www.roh.org.uk/services/venue-hire', heading: enterprises, type: permanent },
  { source: '/weddings', target: 'http://www.roh.org.uk/services/venue-hire/daytime-events/weddings', heading: enterprises, type: permanent },

  # Vanity - marketing
  { source: '/alicesurvey', target: 'http://www.researchnowsurveys.com/survey/VOP21031313001121CSPP/enter.asp', heading: marketing, type: permanent },
  { source: '/aworldstage', target: 'https://www.youtube.com/playlist?list=PL8DF5BB8248AADFC9', heading: marketing, type: permanent },
  { source: '/bolshoi', target: 'http://www.roh.org.uk/about/bolshoi', heading: marketing, type: permanent },
  { source: '/bpbigscreens', target: 'http://www.roh.org.uk/about/bp-big-screens', heading: marketing, type: permanent },
  { source: '/branding', target: 'http://www.roh.org.uk/for/press-and-communications/branding', heading: marketing, type: permanent },
  { source: '/christmas', target: 'http://www.roh.org.uk/about/christmas', heading: marketing, type: permanent },
  { source: '/cinemasurvey', target: 'http://www.surveymonkey.com/s/ROHCinema', heading: marketing, type: permanent },
  { source: '/cinemasurvey-BR', target: 'http://www.surveymonkey.com/s/ROHCinemaBR', heading: marketing, type: permanent },
  { source: '/cinemasurvey-DE', target: 'http://www.surveymonkey.com/s/ROHCinemaDE', heading: marketing, type: permanent },
  { source: '/cinemasurvey-ES', target: 'http://www.surveymonkey.com/s/ROHCinemaES', heading: marketing, type: permanent },
  { source: '/cinemasurvey-FR', target: 'http://www.surveymonkey.com/s/ROHCinemaFRA', heading: marketing, type: permanent },
  { source: '/cinemasurvey-IT', target: 'http://www.surveymonkey.com/s/ROHCinemaIT', heading: marketing, type: permanent },
  { source: '/cinemasurvey-SE', target: 'http://www.surveymonkey.com/s/ROHCinemaSE', heading: marketing, type: permanent },
  { source: '/cyclotrope', target: 'http://www.roh.org.uk/about/deloitte-ignite/the-ring-cyclotrope', heading: marketing, type: permanent },
  { source: '/daytime', target: 'http://www.roh.org.uk/about/daytime-events', heading: marketing, type: permanent },
  { source: '/deloitteignite', target: 'http://www.roh.org.uk/about/deloitte-ignite', heading: marketing, type: permanent },
  { source: '/faustianpack', target: 'http://www.roh.org.uk/productions/faust-by-david-mcvicar?utm_campaign=faust&utm_medium=short&utm_source=marketing', heading: marketing, type: permanent },
  { source: '/groups', target: 'http://www.roh.org.uk/visit/tickets/group-bookings', heading: marketing, type: permanent },
  { source: '/lovepotion', target: 'http://www.roh.org.uk/events/27100/tickets?utm_source=mumsnet&utm_medium=eventpost&utm_campaign=2014_Oct_Welcome_Performances_Elisir', heading: marketing, type: permanent },
  { source: '/mariinsky', target: 'http://www.roh.org.uk/about/mariinsky?utm_source=print&utm_medium=short&utm_campaign=mariinsky', heading: marketing, type: permanent },
  { source: '/montreux', target: 'http://www.roh.org.uk/news/montreux-jazz-festival', heading: marketing, type: permanent },
  { source: '/nye', target: 'http://www.roh.org.uk/visit/restaurants-and-bars/new-years-eve-party', heading: marketing, type: permanent },
  { source: '/openup', target: 'http://www.roh.org.uk/about/open-up?utm_campaign=openup&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/owl', target: 'http://www.roh.org.uk/about/the-owl-and-the-pussycat', heading: marketing, type: permanent },
  { source: '/owls', target: 'http://www.roh.org.uk/about/the-owl-and-the-pussycat', heading: marketing, type: permanent },
  { source: '/pappano', target: 'http://www.roh.org.uk/people/antonio-pappano?utm_campaign=pappano&utm_medium=bimonthly&utm_source=print', heading: marketing, type: permanent },
  { source: '/patisserievalerie', target: 'http://digital.akauk.com/royaloperahouse/patisserievalerie/', heading: marketing, type: permanent },
  { source: '/theolympicjourney', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: marketing, type: permanent },
  { source: '/thering', target: 'http://www.roh.org.uk/about/the-ring', heading: marketing, type: permanent },
  { source: '/thurrocksummer', target: 'http://www.roh.org.uk/news/fused-2015-a-festival-of-choruses-and-costume-with-roh-thurrock', heading: marketing, type: permanent },
  { source: '/worldstage', target: 'https://www.youtube.com/playlist?list=PL8DF5BB8248AADFC9', heading: marketing, type: permanent },
  { source: '/eurydice', target: 'http://www.roh.org.uk/productions/orphee-et-eurydice-by-hofesh-shechter-and-john-fulljames?utm_campaign=eurydice&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/macbeth', target: 'http://www.roh.org.uk/productions/macbeth-by-ted-huffman?utm_campaign=macbeth&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/littlebulb', target: 'http://www.roh.org.uk/productions/orpheus-by-alexander-scott?utm_campaign=littlebulb&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/lighthouse', target: 'http://www.roh.org.uk/productions/meet-the-young-artists-week-performance-by-jette-parker-young-artists?utm_campaign=lighthouse&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/lasthotel', target: 'http://www.roh.org.uk/productions/the-last-hotel-by-enda-walsh?utm_campaign=lasthotel&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/lulu', target: 'http://www.roh.org.uk/productions/lulu-a-murder-ballad-by-mark-holthusen?utm_campaign=lulu&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/orpheus', target: 'http://www.roh.org.uk/productions/orpheus-by-keith-warner?utm_campaign=orpheus&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/alice', target: 'http://www.roh.org.uk/productions/alices-adventures-in-wonderland-by-martin-duncan?utm_campaign=alice&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/morgenundabend', target: 'http://www.roh.org.uk/productions/morgen-und-abend-by-graham-vick?utm_campaign=morgenundabend&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/cavandpag', target: 'http://www.roh.org.uk/mixed-programmes/cavalleria-rusticana-pagliacci?utm_campaign=cavandpag&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/firework-maker', target: 'http://www.roh.org.uk/productions/the-firework-makers-daughter-by-john-fulljames?utm_campaign=firework-maker&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/romeoandjuliet', target: 'http://www.roh.org.uk/productions/romeo-and-juliet-by-kenneth-macmillan?utm_campaign=romeoandjuliet&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/caspublic', target: 'http://www.roh.org.uk/productions/symphonie-dramatique-by-helene-blackburn?utm_campaign=caspublic&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/cheri', target: 'http://www.roh.org.uk/productions/cheri-by-martha-clarke?utm_campaign=cheri&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/connectomemixed', target: 'http://www.roh.org.uk/mixed-programmes/connectome-raven-girl?utm_campaign=connectomemixed&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/carmenmixed', target: 'http://www.roh.org.uk/mixed-programmes/viscera-afternoon-of-a-faun-tchaikovsky-pas-de-deux-carmen?utm_campaign=carmenmixed&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/phoenixdancetheatre', target: 'http://www.roh.org.uk/productions/mixed-programme-untilwithoutenough-tearfall-bloom-by-phoenix-dance-theatre?utm_campaign=phoenixdancetheatre&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/royalnewzealandballet', target: 'http://www.roh.org.uk/productions/mixed-programme-the-anatomy-of-a-passing-cloud-by-royal-new-zealand-ballet?utm_campaign=royalnewzealandballet&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },
  { source: '/pigeonsmixed', target: 'http://www.roh.org.uk/mixed-programmes/monotones-i-and-ii-the-two-pigeons?utm_campaign=pigeonsmixed&utm_medium=marketing&utm_source=print', heading: marketing, type: permanent },

  # Vanity - orphaned events
  { source: '/events/21622/parent', target: 'http://www.roh.org.uk', heading: orphaned, type: permanent },
  { source: '/events/21053/parent', target: 'http://www.roh.org.uk/news/paul-hamlyn-christmas-treat-2012', heading: orphaned, type: permanent },
  { source: '/events/23444/parent', target: 'http://www.roh.org.uk/news/royal-opera-to-stage-lormindo-at-shakespeares-globes-new-sam-wanamaker-playhouse', heading: orphaned, type: permanent },
  { source: '/events/23445/parent', target: 'http://www.roh.org.uk/news/royal-opera-to-stage-lormindo-at-shakespeares-globes-new-sam-wanamaker-playhouse', heading: orphaned, type: permanent },
  { source: '/events/23446/parent', target: 'http://www.roh.org.uk/news/royal-opera-to-stage-lormindo-at-shakespeares-globes-new-sam-wanamaker-playhouse', heading: orphaned, type: permanent },
  { source: '/events/23447/parent', target: 'http://www.roh.org.uk/news/royal-opera-to-stage-lormindo-at-shakespeares-globes-new-sam-wanamaker-playhouse', heading: orphaned, type: permanent },
  { source: '/events/23448/parent', target: 'http://www.roh.org.uk/news/royal-opera-to-stage-lormindo-at-shakespeares-globes-new-sam-wanamaker-playhouse', heading: orphaned, type: permanent },
  { source: '/events/23449/parent', target: 'http://www.roh.org.uk/news/royal-opera-to-stage-lormindo-at-shakespeares-globes-new-sam-wanamaker-playhouse', heading: orphaned, type: permanent },
  { source: '/events/23450/parent', target: 'http://www.roh.org.uk/news/royal-opera-to-stage-lormindo-at-shakespeares-globes-new-sam-wanamaker-playhouse', heading: orphaned, type: permanent },
  { source: '/events/23451/parent', target: 'http://www.roh.org.uk/news/royal-opera-to-stage-lormindo-at-shakespeares-globes-new-sam-wanamaker-playhouse', heading: orphaned, type: permanent },
  { source: '/events/23452/parent', target: 'http://www.roh.org.uk/news/royal-opera-to-stage-lormindo-at-shakespeares-globes-new-sam-wanamaker-playhouse', heading: orphaned, type: permanent },
  { source: '/events/23453/parent', target: 'http://www.roh.org.uk/news/royal-opera-to-stage-lormindo-at-shakespeares-globes-new-sam-wanamaker-playhouse', heading: orphaned, type: permanent },
  { source: '/events/23454/parent', target: 'http://www.roh.org.uk/news/royal-opera-to-stage-lormindo-at-shakespeares-globes-new-sam-wanamaker-playhouse', heading: orphaned, type: permanent },
  { source: '/events/23455/parent', target: 'http://www.roh.org.uk/news/royal-opera-to-stage-lormindo-at-shakespeares-globes-new-sam-wanamaker-playhouse', heading: orphaned, type: permanent },

  # Vanity - hacks
  { source: '/events/3wj2q', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/4sc9q', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/63ykp', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/88bl6', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/9tvvy', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/b68hp', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/c68hh', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/lkfv2', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/m8m55', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/n2zgs', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/q25zx', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/r6nv2', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/shp9s', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/t9c3y', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/wr6vz', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/events/xvlx7', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/productions/deloitte-ignite', target: 'http://www.roh.org.uk/about/deloitte-ignite', heading: hacks, type: permanent },
  { source: '/productions/the-olympic-journey', target: 'http://www.roh.org.uk/about/the-olympic-journey', heading: hacks, type: permanent },
  { source: '/productions/the-owl-and-the-pussycat', target: 'http://www.roh.org.uk/about/the-owl-and-the-pussycat', heading: hacks, type: permanent },
  { source: '/productions/the-owl-and-the-pussycat-by-terry-jones', target: 'http://www.roh.org.uk/about/the-owl-and-the-pussycat', heading: hacks, type: permanent },
  { source: '/about/cinema', target: 'http://www.roh.org.uk/cinemas', heading: hacks, type: permanent },
  { source: '/productions/les-vpres-siciliennes-by-stefan-herheim', target: 'http://www.roh.org.uk/productions/les-vepres-siciliennes-by-stefan-herheim', heading: hacks, type: permanent },
  { source: '/functions/new-years-eve-party', target: 'http://www.roh.org.uk/visit/restaurants-and-bars/new-years-eve-party', heading: hacks, type: permanent },
  { source: '/functions/new-years-eve', target: 'http://www.roh.org.uk/visit/restaurants-and-bars/new-years-eve-party', heading: hacks, type: permanent },
  { source: '/productions/new-years-eve-party', target: 'http://www.roh.org.uk/visit/restaurants-and-bars/new-years-eve-party', heading: hacks, type: permanent },
  { source: '/productions/new-years-eve', target: 'http://www.roh.org.uk/visit/restaurants-and-bars/new-years-eve-party', heading: hacks, type: permanent },
  { source: '/events/k7b43', target: 'http://www.roh.org.uk/visit/restaurants-and-bars/new-years-eve-party', heading: hacks, type: permanent },
  { source: '/events/n85kb', target: 'http://www.roh.org.uk/visit/restaurants-and-bars/new-years-eve-party', heading: hacks, type: permanent },
  { source: '/about/partners/southbank-sinfonia', target: 'http://www.roh.org.uk/about/the-orchestra-of-the-royal-opera-house/southbank-sinfonia', heading: hacks, type: permanent },
  { source: '/learning/roh-collections', target: 'http://www.roh.org.uk/about/roh-collections', heading: hacks, type: permanent },

  # Restructures - people
  { source: '/about/the-royal-ballet/barry-wordsworth', target: 'http://www.roh.org.uk/people/barry-wordsworth', heading: people, type: permanent },
  { source: '/about/the-royal-ballet/christopher-wheeldon', target: 'http://www.roh.org.uk/people/christopher-wheeldon', heading: people, type: permanent },
  { source: '/about/the-royal-ballet/jeanetta-laurence', target: 'http://www.roh.org.uk/people/jeanetta-laurence', heading: people, type: permanent },
  { source: '/about/the-royal-ballet/kevin-ohare', target: 'http://www.roh.org.uk/people/kevin-ohare', heading: people, type: permanent },
  { source: '/about/the-royal-ballet/liam-scarlett', target: 'http://www.roh.org.uk/people/liam-scarlett', heading: people, type: permanent },
  { source: '/about/the-royal-ballet/wayne-mcgregor', target: 'http://www.roh.org.uk/people/wayne-mcgregor', heading: people, type: permanent },
  { source: '/about/the-royal-opera/antonio-pappano', target: 'http://www.roh.org.uk/people/antonio-pappano', heading: people, type: permanent },
  { source: '/about/the-royal-opera/cormac-simms', target: 'http://www.roh.org.uk/people/cormac-simms', heading: people, type: permanent },
  { source: '/about/the-royal-opera/john-fulljames', target: 'http://www.roh.org.uk/people/john-fulljames', heading: people, type: permanent },
  { source: '/about/the-royal-opera/kasper-holten', target: 'http://www.roh.org.uk/people/kasper-holten', heading: people, type: permanent },
  { source: '/about/the-royal-opera/peter-mario-katona', target: 'http://www.roh.org.uk/people/peter-mario-katona', heading: people, type: permanent },
  { source: '/about/the-royal-opera-house/whos-who/alex-beard', target: 'http://www.roh.org.uk/people/alex-beard', heading: people, type: permanent },
  { source: '/about/whos-who/alex-beard', target: 'http://www.roh.org.uk/people/alex-beard', heading: people, type: permanent },

  # Vanity - current site
  { source: '/about/annual-review', target: 'http://www.roh.org.uk/about/the-royal-opera-house/annual-review', heading: curr, type: permanent },
  { source: '/about/roh-connections', target: 'http://www.roh.org.uk/about/roh-links', heading: curr, type: permanent },
  { source: '/about/roh2/deloitte-ignite', target: 'http://www.roh.org.uk/about/deloitte-ignite', heading: curr, type: permanent },
  { source: '/about/venue-hire', target: 'http://www.roh.org.uk/services/venue-hire', heading: curr, type: permanent },
  { source: '/about/whos-who', target: 'http://www.roh.org.uk/about/the-royal-opera-house/whos-who', heading: curr, type: permanent },
  { source: '/about/work-here', target: 'http://www.roh.org.uk/about/the-royal-opera-house/work-here', heading: curr, type: permanent },
  { source: '/backstage-pass', target: 'http://www.roh.org.uk/opera-machine', heading: curr, type: permanent },
  { source: '/backstagepass', target: 'http://www.roh.org.uk/opera-machine', heading: curr, type: permanent },
  { source: '/events/search', target: 'http://www.roh.org.uk/events/ticket-search', heading: curr, type: permanent },
  { source: '/for/students', target: 'http://www.roh.org.uk/for/rohstudents', heading: curr, type: permanent },
  { source: '/for/press-and-media', target: 'http://www.roh.org.uk/for/press-and-communications', heading: curr, type: permanent },
  { source: '/learning/learning-in-thurrock/culture-change', target: 'http://www.roh.org.uk/about/culture-change', heading: curr, type: permanent },
  { source: '/learning/families/community-chorus', target: 'http://www.roh.org.uk/learning/learning-in-thurrock/community-chorus', heading: curr, type: permanent },
  { source: '/news/autumn-201516', target: 'http://www.roh.org.uk/news/autumn-season-201516', heading: curr, type: permanent },
  { source: '/memberships/friend-joint', target: 'http://www.roh.org.uk/memberships/friends-plus', heading: curr, type: permanent },
  { source: '/memberships/friend-supporting', target: 'http://www.roh.org.uk/memberships/supporting-friend', heading: curr, type: permanent },
  { source: '/memberships/friend-premium-1', target: 'http://www.roh.org.uk/memberships/premium-1-friend', heading: curr, type: permanent },
  { source: '/memberships/friend-premium-2', target: 'http://www.roh.org.uk/memberships/premium-2-friend', heading: curr, type: permanent },
  { source: '/memberships/friend-young', target: 'http://www.roh.org.uk/memberships/young-friend', heading: curr, type: permanent },
  { source: '/mixed-programmes/apollo-new-wheeldon-new-ratmansky', target: 'http://www.roh.org.uk/mixed-programmes/apollo-aeternum-24-preludes', heading: curr, type: permanent },
  { source: '/mixed-programmes/cavalleria-pagliacci', target: 'http://www.roh.org.uk/mixed-programmes/cavalleria-rusticana-pagliacci', heading: curr, type: permanent },
  { source: '/mixed-programmes/chroma-new-dawson-the-rite-of-spring', target: 'http://www.roh.org.uk/mixed-programmes/chroma-the-human-seasons-the-rite-of-spring', heading: curr, type: permanent },
  { source: '/mixed-programmes/rhapsody-the-art-of-fugue-gloria', target: 'http://www.roh.org.uk/mixed-programmes/rhapsody-tetractys-the-art-of-fugue-gloria', heading: curr, type: permanent },
  { source: '/mixed-programmes/rhapsody-tetractys-gloria', target: 'http://www.roh.org.uk/mixed-programmes/rhapsody-tetractys-the-art-of-fugue-gloria', heading: curr, type: permanent },
  { source: '/mixed-programmes/serenade-sweet-violets-dgv', target: 'http://www.roh.org.uk/mixed-programmes/serenade-sweet-violets-dgv-danse-a-grande-vitesse', heading: curr, type: permanent },
  { source: '/mixed-programmes/the-dream-new-marriott-the-concert', target: 'http://www.roh.org.uk/mixed-programmes/the-dream-connectome-the-concert', heading: curr, type: permanent },
  { source: '/mixed-programmes/the-four-temperaments-hofesh-shechter-song-of-the-earth', target: 'http://www.roh.org.uk/mixed-programmes/the-four-temperaments-untouchable-song-of-the-earth', heading: curr, type: permanent },
  { source: '/productions/cover-by-itamar-serussi', target: 'http://www.roh.org.uk/productions/shaker-loops-cover-by-various', heading: curr, type: permanent },
  { source: '/productions/cover-shaker-loops-by-various', target: 'http://www.roh.org.uk/productions/shaker-loops-cover-by-various', heading: curr, type: permanent },
  { source: '/productions/il-barbiere-di-siviglia-by-moshe-leiser', target: 'http://www.roh.org.uk/productions/il-barbiere-di-siviglia-by-moshe-leiser-and-patrice-caurier', heading: curr, type: permanent },
  { source: '/productions/il-turco-in-italia-by-moshe-leiser', target: 'http://www.roh.org.uk/productions/il-turco-in-italia-by-moshe-leiser-and-patrice-caurier', heading: curr, type: permanent },
  { source: '/productions/new-dawson-by-david-dawson', target: 'http://www.roh.org.uk/productions/the-human-seasons-by-david-dawson', heading: curr, type: permanent },
  { source: '/productions/new-hofesh-shechter-by-hofesh-shechter', target: 'http://www.roh.org.uk/productions/untouchable-by-hofesh-shechter', heading: curr, type: permanent },
  { source: '/productions/new-marriott-by-alastair-marriott', target: 'http://www.roh.org.uk/productions/connectome-by-alastair-marriott', heading: curr, type: permanent },
  { source: '/productions/new-ratmansky-by-alexei-ratmansky', target: 'http://www.roh.org.uk/productions/24-preludes-by-alexei-ratmansky', heading: curr, type: permanent },
  { source: '/productions/new-wheeldon-by-christopher-wheeldon', target: 'http://www.roh.org.uk/productions/aeternum-by-christopher-wheeldon', heading: curr, type: permanent },
  { source: '/productions/the-art-of-fugue-by-wayne-mcgregor', target: 'http://www.roh.org.uk/productions/tetractys-the-art-of-fugue-by-wayne-mcgregor', heading: curr, type: permanent },
  { source: '/productions/the-cure-the-corridor-by-martin-duncan', target: 'http://www.roh.org.uk/productions/the-corridor-the-cure-by-martin-duncan', heading: curr, type: permanent },
  { source: '/productions/the-elves-and-the-shoemaker-by-daniel-de-andrade', target: 'http://www.roh.org.uk/productions/elves-and-the-shoemaker-by-daniel-de-andrade', heading: curr, type: permanent },
  { source: '/productions/tetractys-the-art-of-fugue-by-wayne-mcgregor', target: 'http://www.roh.org.uk/productions/tetractys-by-wayne-mcgregor', heading: curr, type: permanent },
  { source: '/publications/royal-opera-house-guide-to-don-giovanni', target: 'http://www.roh.org.uk/publications/don-giovanni-digital-programme', heading: curr, type: permanent },
  { source: '/publications/royal-opera-house-guide-to-giselle', target: 'http://www.roh.org.uk/publications/giselle-digital-programme', heading: curr, type: permanent },
  { source: '/publications/royal-opera-house-guide-to-manon-lescaut', target: 'http://www.roh.org.uk/publications/manon-lescaut-digital-programme', heading: curr, type: permanent },
  { source: '/publications/royal-opera-house-guide-to-the-sleeping-beauty', target: 'http://www.roh.org.uk/publications/the-sleeping-beauty-digital-programme', heading: curr, type: permanent },
  { source: '/publications/royal-opera-house-guide-to-the-winters-tale', target: 'http://www.roh.org.uk/publications/the-winters-tale-digital-programme', heading: curr, type: permanent },
  { source: '/support/donations/fundraising-appeals/chance-to-dance-appeal', target: 'http://www.roh.org.uk/support/fundraising-appeals/chance-to-dance-appeal', heading: curr, type: permanent },
  { source: '/support/donations/fundraising-appeals/pointe-shoes-appeal', target: 'http://www.roh.org.uk/support/fundraising-appeals/pointe-shoes-appeal', heading: curr, type: permanent },
  { source: '/support/donations/fundraising-appeals/wagner-appeal', target: 'http://www.roh.org.uk/support/fundraising-appeals/wagner-appeal', heading: curr, type: permanent },
  { source: '/support/donations/fundraising-appeals/season-launch-appeal', heading: curr, type: gone },
  { source: '/support/donations/fundraising-appeals/name-a-seat', target: 'http://www.roh.org.uk/support/name-a-seat', heading: curr, type: permanent },
  { source: '/support/donations/fundraising-appeals', target: 'http://www.roh.org.uk/support/fundraising-appeals', heading: curr, type: permanent },
  { source: '/support/donations/leave-a-legacy/royal-opera-house-endowment-fund', target: 'http://www.roh.org.uk/support/leave-a-legacy/royal-opera-house-endowment-fund', heading: curr, type: permanent },
  { source: '/support/donations/leave-a-legacy/baton-associates', target: 'http://www.roh.org.uk/support/leave-a-legacy/baton-associates', heading: curr, type: permanent },
  { source: '/support/donations/leave-a-legacy', target: 'http://www.roh.org.uk/support/leave-a-legacy', heading: curr, type: permanent },
  { source: '/support/donations/support-a-circle/royal-opera-circle', target: 'http://www.roh.org.uk/support/deepen-your-involvement/support-a-circle/royal-opera-circle', heading: curr, type: permanent },
  { source: '/support/donations/support-a-circle/connoisseurs-series', target: 'http://www.roh.org.uk/support/deepen-your-involvement/support-a-circle/connoisseurs-series', heading: curr, type: permanent },
  { source: '/support/donations/support-a-circle/maestros-circle', target: 'http://www.roh.org.uk/support/deepen-your-involvement/support-a-circle/maestros-circle', heading: curr, type: permanent },
  { source: '/support/donations/support-a-circle/artists-circle', target: 'http://www.roh.org.uk/support/deepen-your-involvement/support-a-circle/artists-circle', heading: curr, type: permanent },
  { source: '/support/donations/support-a-circle/fonteyn-circle', target: 'http://www.roh.org.uk/support/deepen-your-involvement/support-a-circle/fonteyn-circle', heading: curr, type: permanent },
  { source: '/support/donations/support-a-circle/wagner-circle', target: 'http://www.roh.org.uk/support/deepen-your-involvement/support-a-circle/wagner-circle', heading: curr, type: permanent },
  { source: '/support/donations/support-a-circle', target: 'http://www.roh.org.uk/support/deepen-your-involvement/support-a-circle', heading: curr, type: permanent },
  { source: '/support/donations/support-a-production', target: 'http://www.roh.org.uk/support/deepen-your-involvement/support-a-production', heading: curr, type: permanent },
  { source: '/support/donations/special-events', target: 'http://www.roh.org.uk/support/deepen-your-involvement/special-events', heading: curr, type: permanent },
  { source: '/support/donations', target: 'http://www.roh.org.uk/support/donate-now', heading: curr, type: permanent },
  { source: '/support/trusts-and-foundations/laura-ashley-foundation', target: 'http://www.roh.org.uk/support/trusts-and-foundations', heading: curr, type: permanent },
  { source: '/support/trusts-and-foundations/the-helen-hamlyn-trust', target: 'http://www.roh.org.uk/support/trusts-and-foundations', heading: curr, type: permanent },
  { source: '/support/you/artists-circle', target: 'http://www.roh.org.uk/support/donations-and-support/support-a-circle/artists-circle', heading: curr, type: permanent },
  { source: '/support/you/baton-associates', target: 'http://www.roh.org.uk/support/donations-and-support/leave-a-legacy/baton-associates', heading: curr, type: permanent },
  { source: '/support/you/connoisseurs-series', target: 'http://www.roh.org.uk/support/donations-and-support/support-a-circle/connoisseurs-series', heading: curr, type: permanent },
  { source: '/support/you/covent-garden-insiders', target: 'http://www.roh.org.uk/support/membership/friends', heading: curr, type: permanent },
  { source: '/support/you/covent-garden-supporters', target: 'http://www.roh.org.uk/support/royal-opera-house-supporters', heading: curr, type: permanent },
  { source: '/support/you/fonteyn-circle', target: 'http://www.roh.org.uk/support/donations-and-support/support-a-circle/the-fonteyn-circle', heading: curr, type: permanent },
  { source: '/support/you/friends', target: 'http://www.roh.org.uk/support/membership/friends', heading: curr, type: permanent },
  { source: '/support/you/leaving-a-legacy', target: 'http://www.roh.org.uk/support/donations-and-support/leave-a-legacy', heading: curr, type: permanent },
  { source: '/support/you/name-a-seat', target: 'http://www.roh.org.uk/support/donations-and-support/fundraising-appeals/name-a-seat', heading: curr, type: permanent },
  { source: '/support/you/patrons', target: 'http://www.roh.org.uk/support/membership/patrons', heading: curr, type: permanent },
  { source: '/support/you/pointe-appeal', target: 'http://www.roh.org.uk/support/donations-and-support/fundraising-appeals/pointe-shoes-appeal', heading: curr, type: permanent },
  { source: '/support/you/premium-and-supporting-friends', target: 'http://www.roh.org.uk/support/royal-opera-house-supporters', heading: curr, type: permanent },
  { source: '/support/you/production-syndicates', target: 'http://www.roh.org.uk/support/donations-and-support/support-a-production', heading: curr, type: permanent },
  { source: '/support/you/royal-opera-house-endowment-fund', target: 'http://www.roh.org.uk/support/donations-and-support/leave-a-legacy/royal-opera-house-endowment-fund', heading: curr, type: permanent },
  { source: '/support/you/the-maestros-circle', target: 'http://www.roh.org.uk/support/donations-and-support/support-a-circle/the-maestros-circle', heading: curr, type: permanent },
  { source: '/support/you/the-wagner-circle', target: 'http://www.roh.org.uk/support/donations-and-support/support-a-circle/the-wagner-circle', heading: curr, type: permanent },
  { source: '/support/you', target: 'http://www.roh.org.uk/support/membership', heading: curr, type: permanent },
  { source: '/support/your-business/benefits-in-brief', target: 'http://www.roh.org.uk/support/membership/patrons/corporate-patrons', heading: curr, type: permanent },
  { source: '/support/your-business/corporate-membership-fees', target: 'http://www.roh.org.uk/support/membership/patrons/corporate-patrons', heading: curr, type: permanent },
  { source: '/support/your-business/corporate-patrons', target: 'http://www.roh.org.uk/support/membership/patrons/corporate-patrons', heading: curr, type: permanent },
  { source: '/support/your-business/corporate-sponsorship', target: 'http://www.roh.org.uk/support/sponsorship-and-hospitality', heading: curr, type: permanent },
  { source: '/support/your-business', target: 'http://www.roh.org.uk/support/sponsorship-and-hospitality', heading: curr, type: permanent },
  { source: '/support/donations-and-support/support-a-circle/the-fonteyn-circle', target: 'http://www.roh.org.uk/support/donations/support-a-circle/fonteyn-circle', heading: curr, type: permanent },
  { source: '/support/donations-and-support/support-a-circle/the-maestros-circle', target: 'http://www.roh.org.uk/support/donations/support-a-circle/maestros-circle', heading: curr, type: permanent },
  { source: '/support/donations-and-support/support-a-circle/the-wagner-circle', target: 'http://www.roh.org.uk/support/donations/support-a-circle/wagner-circle', heading: curr, type: permanent },
  { source: '/support/donations-and-support/support-a-circle/fonteyn-circle', target: 'http://www.roh.org.uk/support/donations/support-a-circle/fonteyn-circle', heading: curr, type: permanent },
  { source: '/support/donations-and-support/support-a-circle/maestros-circle', target: 'http://www.roh.org.uk/support/donations/support-a-circle/maestros-circle', heading: curr, type: permanent },
  { source: '/support/donations-and-support/support-a-circle/wagner-circle', target: 'http://www.roh.org.uk/support/donations/support-a-circle/wagner-circle', heading: curr, type: permanent },
  { source: '/support/donations-and-support/support-a-circle/connoisseurs-series', target: 'http://www.roh.org.uk/support/donations/support-a-circle/connoisseurs-series', heading: curr, type: permanent },
  { source: '/support/donations-and-support/support-a-circle/artists-circle', target: 'http://www.roh.org.uk/support/donations/support-a-circle/artists-circle', heading: curr, type: permanent },
  { source: '/support/donations-and-support/support-a-circle', target: 'http://www.roh.org.uk/support/donations/support-a-circle', heading: curr, type: permanent },
  { source: '/support/donations-and-support/support-a-production', target: 'http://www.roh.org.uk/support/donations/support-a-production', heading: curr, type: permanent },
  { source: '/support/donations-and-support/leave-a-legacy/royal-opera-house-endowment-fund', target: 'http://www.roh.org.uk/support/donations/leave-a-legacy/royal-opera-house-endowment-fund', heading: curr, type: permanent },
  { source: '/support/donations-and-support/leave-a-legacy/baton-associates', target: 'http://www.roh.org.uk/support/donations/leave-a-legacy/baton-associates', heading: curr, type: permanent },
  { source: '/support/donations-and-support/leave-a-legacy', target: 'http://www.roh.org.uk/support/donations/leave-a-legacy', heading: curr, type: permanent },
  { source: '/support/donations-and-support/fundraising-appeals/pointe-shoes-appeal', target: 'http://www.roh.org.uk/support/donations/fundraising-appeals/pointe-shoes-appeal', heading: curr, type: permanent },
  { source: '/support/donations-and-support/fundraising-appeals/name-a-seat', target: 'http://www.roh.org.uk/support/donations/fundraising-appeals/name-a-seat', heading: curr, type: permanent },
  { source: '/support/donations-and-support/fundraising-appeals', target: 'http://www.roh.org.uk/support/donations/fundraising-appeals', heading: curr, type: permanent },
  { source: '/support/donations-and-support/special-events', target: 'http://www.roh.org.uk/support/donations/special-events', heading: curr, type: permanent },
  { source: '/support/donations-and-support', target: 'http://www.roh.org.uk/support/donations', heading: curr, type: permanent },
  { source: '/support/corporate-involvement/sponsorship-opportunities', target: 'http://www.roh.org.uk/support/sponsorship-and-hospitality', heading: curr, type: permanent },
  { source: '/support/corporate-involvement', target: 'http://www.roh.org.uk/support/sponsorship-and-hospitality', heading: curr, type: permanent },
  { source: '/services/venue-hire/the-linbury-theatre-and-foyer', target: 'http://www.roh.org.uk/services/venue-hire/the-linbury-studio-theatre-and-foyer', heading: curr, type: permanent },
  { source: '/visit/group-bookings', target: 'http://www.roh.org.uk/visit/tickets/group-bookings', heading: curr, type: permanent }
])
